#!bin/bash
#done
#(come to the lake) - move to Lake Directory

echo "Following the route. You come across a calm body of water. This appears to a surrounding tree landscape with no movement."
sleep 1;
echo "You feel eerily calm, but are in no rush to leave."
sleep 1;
echo "You scout out a dark deeper part of the lake to your left, an arch way looming directly infront of you and across the lake leading to a lush green garden."
echo " Then to your right you spot an eery unmarked path with dark vines and dead looking trees."
sleep 1;
echo "Before deciding whether to continue on with any of these paths, you spot a bubbling mark appear on the otherwise smooth lake surface."
sleep 1;
echo "You move closer to get a clearer view of the movement, as a head begins to slowly rises. A woman emerges."
sleep 1;
tput bold; echo "Lady of the Lake: "; tput sgr0; echo "Hello traveler. You must be unaware of what is happening."
sleep 1;
while [[ $REPLY != 0 ]] 
do
cat <<EOF
        1. Who are you?
        2. Someone called out to me with this amulet.
EOF
    read -p "" selection4
          case $selection4 in
          1)
              echo "I am the Lady of this Lake. I come from this fair land of Avalon, a community laying below this reservoir."
              sleep 1;
              echo "The Lady turns toward the deeper lake, directing you to see that part of the lake."
              sleep 1;
              tput bold; echo "Lady of the Lake: "; tput sgr0; echo "Follow this path. There is an item you will need. It is most important for your travels."
              sleep 1;
              echo "She turns to you."
              sleep 1;
              tput bold; echo "Lady of the Lake: "; tput sgr0; echo "Travel quietly. Don't be fooled by the beings who are there, they only have your worst interests in mind."
              sleep 1;
              echo "Once you get this item, come back here and head through the archway."
              sleep 1;
              echo "She proceeds to turn around, walking gracefully into the water to see ripples dissipate."
              sleep 1;
              echo "Press any button to continue: "
              read hi
              clear
              break
              ;;
          2)
              echo "You take the necklace off and show her. She briefly grabs onto it and studies it's design intently. She then proceeds to hand it back."
              sleep 1;
              tput bold; echo "Lady of the Lake"; tput sgr0; echo "That amulet is not mine, but I know of the being to whom it belongs."
              sleep 1;
              echo "The Lady turns toward the deeper lake, directing you to see the deeper part of the lake."
              sleep 1;
              tput bold; echo "Lady of the Lake: "; tput sgr0; echo "Follow this path. There is an item you will need. It is most important for your travels."
              sleep 1;
              echo "She turns to you."
              sleep 1;
              tput bold; echo "Lady of the Lake: "; tput sgr0; echo "Travel quietly. Don't be fooled by the beings who are there, they only have your worst interests in mind."
              sleep 1;
              echo "Once you get this item, come back here and head through the archway. You shall soon meet the being who speaks trough your amulet."
              sleep 1;
              echo "She proceeds to turn around, walking gracefully into the water to see ripples dissipate."
              sleep 1;
              echo "Press any button to continue: "
              read hi
              clear
              break
              ;;
            *)
              ;;
esac
done
rm $location/locations/cave/barn/lake/@Lake

