#!bin/bash/

#(Arrive at spooky area) - move to Bridge Directory

echo "You travel to the dead part of the forest."
sleep 1;
echo "You take some bends around to then come across a bridge over a gigantic moat."
sleep 1;
echo "You look ahead to start walking over the dridge, when it begins to rise."
sleep 1;
echo "You see a big reptilian creature looking directly at you as the bridge closes."
sleep 1;
echo "You cannot cross over to the castle."
sleep 1;
echo "looking at the giant moat before you, a sparkling flask of a deep maroon color stands out to you against the moats bank."
mv .+strength-potion \+strength-potion
bridgeraise="yes";
if [ -e "$collected/+potion-of-bezoar" ] || [ "$potionused" = "yes" ]
then
echo "You decide to head back and speak with Merlin again."
mv $location/locations/cave/barn/lake/garden/merlin_tower/.@Merlin4 $location/locations/cave/barn/lake/garden/merlin_tower/@Merlin4
else 
echo ""
fi
if [ "$itemseen" = "no" ]
  then
          tput bold; echo "Amulet: " ; tput sgr0 ; echo "Over the course of your journey you may also find some flasks or stones,"
          echo "these items are used to heal yourself or increase your damage."
          sleep 1;
          echo "To use these materials you must use this command."
          sleep 1;
          echo "useItem" 
          sleep 1;
          echo "        -> This command gives you a prompt for which item to use and will then remove that item from collected." 
          sleep 1;
          echo "(If you are unsure which items you are able to use remember the command below)" 
          sleep 1;
          echo " -> view collected items: ls \$collected"  >> "$location/scripts/listofcommands"
          echo "To use these materials you must use this command." >> "$location/scripts/listofcommands"
          echo "useItem" >> "$location/scripts/listofcommands"
          echo "        -> This command gives you a prompt for which item to use and will then remove that item from collected." >> "$location/scripts/listofcommands"
          echo "(If you are unsure which items you are able to use remember the command below)" >> "$location/scripts/listofcommands"
          echo " -> view collected items: ls \$collected" >> "$location/scripts/listofcommands"
          itemseen="yes"
  fi
echo "Press any button to continue: "
read hi
clear
