#!bin/bash/

#(Arrive at spooky area) - move to Bridge Directory

echo "You travel to the dead part of the forest."
sleep 1;
echo "You take some bends around to then come across a bridge over a gigantic moat."
sleep 1;
echo "You look ahead to start walking over the dridge, when it begins to rise."
sleep 1;
echo "You see a big reptilian creature looking directly at you as the bridge closes."
sleep 1;
echo "You cannot cross over to the castle."
sleep 1;
echo "looking at the giant moat before you, a sparkling flask of a deep maroon color stands out to you against the moats bank."
mv .+Strength-Potion \+Strength-Potion
bridgeraise="yes";
if [ -e \+Potion-Of-Bezoar $location/collected ]
then
echo "You decide to head back and speak with Merlin again."
mv $location/locations/cave/barn/lake/garden/merlin_tower/.@Merlin4 $location/locations/cave/barn/lake/garden/merlin_tower/@Merlin4
fi
echo "Press any button to continue: "
read hi
clear
