#!bin/bash/

#(Arrive at spooky area) - move to Bridge Directory

echo "You travel to the dead part of the forest. You take some bends around to then come across a bridge over a gigantic moat. You look ahead to start walking over the dridge, when it begins to rise. You see a big reptilian creature looking directly at you as the bridge closes. You cannot cross over to the castle. You decide to head back and speak with Merlin again."
