#!bin/bash/

#(meet at tower) - Move to Tower Directory 

echo "You hand merlin the basil plant. He takes the basil, carefully tearing the leaves and letting them float on the ground."
echo "He throws the stem and grabs a unknown book from behind him."
tput bold; echo "Merlin: "; tput srg0; echo "Take this, a Potion of Bezoar. This should help you when you face off. Just make sure to drink it beforehand."
echo "You obtained a potion!"
tput bold; echo "Merlin: "; tput srg0; echo "I can see that you have everything you need. Head to the bridge next to the lake."
echo "It should take you directly to the castle and face off with the credent."
