#!bin/bash

#Merlin Tower(goes to tower after garden) - move to Tower Directory/continue from tower directory in Option Uno 

echo "Travelling around some bends by trees and curvy path structure, you come across a giant tower. You notice the phoenix fly high to a balcony, landing for a second on a railing looking at a figure inside. You see the bird take off and fly towards the entrance on the ground, as the door slowly opens."
echo "You approach the open door and see a man emerge. He appears to be of older age, wearing a matching gown and pointed had. You stop as he slowly waddles to you."
tput bold; echo "Merlin: "; tput srg0; echo "I was the one talking to you through the talisman you are wearing. My name is Merlin. I am a protector of these lands against evil. This is my companion. I had him lead you here to me to ask you, $name, for help."

while [[ $REPLY != 0 ]]; do
cat <<EOF
        1. Why do you need me to help you?
        2. What do you need me to do?
EOF
    read -p "" selection6
        case $selection6 in
        1)
            echo "Cornwall is in dismay. Legend has it that an adventurer of unknown origins will come to slay the beast glooming over the land. I believe that hero is you."
            ;;
        2)
            echo "I need you to go on a fetch quest. The basilisk is a prickly fellow. His gaze is a deadly weapon. One glance and your done for. I can make invulnerable if you can get the basil herb. There is a chest-locked away with this herb. However, there is a key you need for it. It should just be down towards cemetery along the path at the garden you did not take."
            ;;
esac
