#!/bin/bash

location=$PWD

function beastiary () {
	i=0
	echo "                      Beastiary                      "
	echo "-----------------------------------------------------"
	echo ""
	echo ""
	echo ""
	echo "$i) Exit Beastiary"
	for FILE in $location/beastiary; ((i = i + 1)); echo "$i) Read " FILE " description";

}
function reset_var () {	
talisman="no"
excalibur="no"
skull-key="no"
centaur="no"
egg="no"
griffen="no"
spell="no"
skeleton="no"
ladyofthelake="no"
phoenix="no"
merlin="no"
siren="no"
basilisk="no"
}

export name
export talisman
export excalibur
export skull-key
export centaur
export griffen
export egg
export spell
export skeleton
export imp
export phoenix
export ladyofthelake
export merlin
export siren
export basilisk

function move_items () {
  cp $location/collection/.talisman $location/collection/talisman
  mv $location/collection/talisman $location/collected
  rm $location/collection/.talisman
  cp $location/collection/.excalibur $location/collection/excalibur
  mv $location/collection/excalibur $location/collected
  rm $location/collection/.excalibur
  cp $location/collection/.skull-key $location/collection/skull-key
  mv $location/collection/skull-key $location/collected
  rm $location/collection/.skull-key
  cp /LARK-Project-/collection/.centaur /LARK-Project-/collection/centaur
  mv /LARK-Project-/collection/centaur /LARK-Project-/collected
  rm /LARK-Project-/collection/.centaur
  cp /LARK-Project-/collection/.griffen /LARK-Project-/collection/griffen
  mv /LARK-Project-/collection/griffen /LARK-Project-/collected
  rm /LARK-Project-/collection/.griffen
  cp /LARK-Project-/collection/.egg /LARK-Project-/collection/egg
  mv /LARK-Project-/collection/egg /LARK-Project-/collected
  rm /LARK-Project-/collection/.egg
  cp /LARK-Project-/collection/.spell /LARK-Project-/collection/spell
  mv /LARK-Project-/collection/spell /LARK-Project-/collected
  rm /LARK-Project-/collection/.spell
  cp /LARK-Project-/collection/.skeleton /LARK-Project-/collection/skeleton
  mv /LARK-Project-/collection/skeleton /LARK-Project-/collected
  rm /LARK-Project-/collection/.skeleton
  cp /LARK-Project-/collection/.imp /LARK-Project-/collection/imp
  mv /LARK-Project-/collection/imp /LARK-Project-/collected
  rm /LARK-Project-/collection/.imp
  cp /LARK-Project-/collection/.phoenix /LARK-Project-/collection/phoenix
  mv /LARK-Project-/collection/phoenix /LARK-Project-/collected
  rm /LARK-Project-/collection/.phoenix
  cp /LARK-Project-/collection/.ladyofthelake /LARK-Project-/collection/ladyofthelake
  mv /LARK-Project-/collection/ladyofthelake /LARK-Project-/collected
  rm /LARK-Project-/collection/.ladyofthelake
  cp /LARK-Project-/collection/.merlin /LARK-Project-/collection/merlin
  mv /LARK-Project-/collection/merlin /LARK-Project-/collected
  rm /LARK-Project-/collection/.merlin
  cp /LARK-Project-/collection/.siren /LARK-Project-/collection/siren
  mv /LARK-Project-/collection/siren /LARK-Project-/collected
  rm /LARK-Project-/collection/.siren
  cp /LARK-Project-/collection/.basilisk /LARK-Project-/collection/basilisk
  mv /LARK-Project-/collection/basilisk /LARK-Project-/collected
  rm /LARK-Project-/collection/.basilisk
}
talisman() { less "$location/scripts/commandList"; }

tput smcup
while [[ $REPLY != "c" ]]
do
clear 
  cat <<EOF
	      Menu
	~~~~~~~~~~~~~~~~~
	a. Start Game
	b. About Game
	c. Quit


EOF
	read -p "Enter choice [a-c]: " choice
	move_items
	reset_var
	
	case $choice in 
	a) echo "Your Story can now begin"
	sleep 1;
	read -p "Enter a name of the Legend: " name
	sleep 1;
	echo "Excellent. Now it is time to tell the story of our new hero $name."
	sleep 1;
	echo "(If at any point you need to exit the game, just type _____.)"
	sleep 1;
	echo "(This game does require you to search around for items. Make sure to pick them up along the way, as they will be needed for you to continue on your journey.)"
	. start
	;;
	b) clear 
	echo "___________ is a terminal based game that was made to showcase a few basics commands used in the linux terminal.
	This is done so that the player can learn a bit about how to utilize the bash shell in an entertaining way.
	To begin the game be sure to choose option a). After choosing option a) your goal as the hero of this story is to explore this mystical forest and confront the evil being causing more and more evils to infect this peaceful land.
	
	If you wish to avoid seeing and altering any of the game code be sure to follow the games instructions."
	sleep 1;
	;;
	c) 
	tput rmcup
	echo "Exiting Game"
	break
	;;
	*) echo "Invalid Option: Make sure to enter only [a-c] for this menu."
	;;
esac
done
