#!/bin/bash

location=$PWD

function reset_var()
{	
talisman="no"
excalibur="no"
skull-key="no"
centaur="no"
egg="no"
griffen="no"
spell="no"
skeleton="no"
ladyofthelake="no"
phoenix="no"
merlin="no"
siren="no"
basilisk="no"
}

export name
export talisman
export excalibur
export skull-key
export centaur
export griffen
export egg
export spell
export skeleton
export imp
export phoenix
export ladyofthelake
export merlin
export siren
export basilisk

function move_items() 
{
  cp $location/collection/.talisman $location/collection/talisman
  mv $location/collection/talisman $location/collected
  rm $location/collection/.talisman
  cp $location/collection/.excalibur $location/collection/excalibur
  mv $location/collection/excalibur $location/collected
  rm $location/collection/.excalibur
  cp $location/collection/.skull-key $location/collection/skull-key
  mv $location/collection/skull-key $location/collected
  rm $location/collection/.skull-key
  cp /LARK-Project-/collection/.centaur /LARK-Project-/collection/centaur
  mv /LARK-Project-/collection/centaur /LARK-Project-/collected
  rm /LARK-Project-/collection/.centaur
  cp /LARK-Project-/collection/.griffen /LARK-Project-/collection/griffen
  mv /LARK-Project-/collection/griffen /LARK-Project-/collected
  rm /LARK-Project-/collection/.griffen
  cp /LARK-Project-/collection/.egg /LARK-Project-/collection/egg
  mv /LARK-Project-/collection/egg /LARK-Project-/collected
  rm /LARK-Project-/collection/.egg
  cp /LARK-Project-/collection/.spell /LARK-Project-/collection/spell
  mv /LARK-Project-/collection/spell /LARK-Project-/collected
  rm /LARK-Project-/collection/.spell
  cp /LARK-Project-/collection/.skeleton /LARK-Project-/collection/skeleton
  mv /LARK-Project-/collection/skeleton /LARK-Project-/collected
  rm /LARK-Project-/collection/.skeleton
  cp /LARK-Project-/collection/.imp /LARK-Project-/collection/imp
  mv /LARK-Project-/collection/imp /LARK-Project-/collected
  rm /LARK-Project-/collection/.imp
  cp /LARK-Project-/collection/.phoenix /LARK-Project-/collection/phoenix
  mv /LARK-Project-/collection/phoenix /LARK-Project-/collected
  rm /LARK-Project-/collection/.phoenix
  cp /LARK-Project-/collection/.ladyofthelake /LARK-Project-/collection/ladyofthelake
  mv /LARK-Project-/collection/ladyofthelake /LARK-Project-/collected
  rm /LARK-Project-/collection/.ladyofthelake
  cp /LARK-Project-/collection/.merlin /LARK-Project-/collection/merlin
  mv /LARK-Project-/collection/merlin /LARK-Project-/collected
  rm /LARK-Project-/collection/.merlin
  cp /LARK-Project-/collection/.siren /LARK-Project-/collection/siren
  mv /LARK-Project-/collection/siren /LARK-Project-/collected
  rm /LARK-Project-/collection/.siren
  cp /LARK-Project-/collection/.basilisk /LARK-Project-/collection/basilisk
  mv /LARK-Project-/collection/basilisk /LARK-Project-/collected
  rm /LARK-Project-/collection/.basilisk
}

echo "This game does require you to search around for items. Make sure to pick them up along the way, as they will be needed for you to continue on your journey."

sleep 10;

echo "If at any point you need to exit the game, just type _____."

sleep 10;

read -p "Enter a name of the Legend: " name
echo "Excellent. Now it is time to tell the story of our new hero $name."

sleep 10;
