#!/bin/bash

location=$PWD
collected=$location/collected
function reset_var () {	
bridgeraise="no"
potionused="no"
attack=2
health=25
defense=0
maxhealth=20
lives=3


export lives
export potionused
export bridgeraise
export maxhealth
export health
export attack
export defense
export location
export name
export collected
}

function true_reset () {
unset lives
unset potionused
unset bridgeraise
unset maxhealth
unset health
unset attack
unset defense
unset location
unset name
unset collected
}

function move_items() {
  for FILE in $collected; do rm $collected/FILE; done
  mv $+amulet /$collected 2>/dev/null
  rm $location/locations/cave/barn/.+rusted-platemail 2>/dev/null
  rm $location/locations/cave/barn/+rusted-platemail 2>/dev/null
  cp $location/collection/.+rusted-platemail $location/locations/cave/barn/ 2>/dev/null
  rm $location/locations/cave/barn/lake/.+whetstone
  rm $location/locations/cave/barn/lake/+whetstone
  
  
}
amulet() { less "$location/scripts/listofcommands"; }
function useItem() { 
	echo "Enter item to be used (if it is inside of collected)"
	echo "
	0. none
	1. +health-potion
	2. +whetstone
	3. +strength-potion
	4. +strong-strength-potion
	5. +strong-health-potion
	6. +potion-of-bezoar
	7. +medium-health-potion
	"
	read choice2
	case $choice2 in
		*)
			echo "no item used"
			echo "press any button to continue"
			read hi
			clear
		;;
		1)
			if [ -e "$collected/+health-potion" ]
			then 
			health=$(( $health + 15 ));
			if [ "$health" -gt "$maxhealth" ]
			then 
			health=$(( $maxhealth ));
			fi
			echo "$name healed"
			rm $collected/+health-potion
			PS1="[ $name: $health $attack $defense ] "
			echo "press any button to continue"
			read hi
			clear
			else 
			echo "The health-potion is not currently collected"
			echo "press any button to continue"
			read hi
			clear
			fi
		;;
		2)
			if [ -e "$collected/+whetstone" ]
			then
			attack=$(( $attack + 2 ));
			echo "Attack increased"
			rm $collected/+whetstone
			PS1="[ $name: $health $attack $defense ] "
			echo "press any button to continue"
			read hi
			clear
			else 
			echo "The whetstone is not currently collected"
			echo "press any button to continue"
			read hi
			clear
			fi
		;;
		3)
			if [ -e "$collected/+strength-potion" ]
			then
			attack=$(( $attack + 2 ));
			echo "Attack increased"
			rm $collected/+strength-potion
			PS1="[ $name: $health $attack $defense ] "
			echo "press any button to continue"
			read hi
			clear
			else 
			echo "The strength-potion is not currently collected"
			echo "press any button to continue"
			read hi
			clear
			fi
		;;
		4)
			if [ -e "$collected/+strong-strength-potion" ]
			then
			attack=$(( $attack + 4 ));
			echo "Attack increased"
			rm $collected/+strong-attack-potion
			PS1="[ $name: $health $attack $defense ] "
			echo "press any button to continue"
			read hi
			clear
			else 
			echo "The strong-strength-potion is not currently collected"
			echo "press any button to continue"
			read hi
			clear
			fi
		;;
		5)
			if [ -e "$collected/+strong-health-potion" ]
			then
			health=$(( $health + 50 ));
			if [ "$health" -gt "$maxhealth" ]
			then
			health=$(( $maxhealth ));
			fi
			echo "$name healed"
			rm $collected/+strong-health-potion
			PS1="[ $name: $health $attack $defense ] "
			echo "press any button to continue"
			read hi
			clear
			else 
			echo "The strong-health-potion is not currently collected"
			echo "press any button to continue"
			read hi
			clear
			fi
		;;
		6)
			if [ -e "$collected/+potion-of-bezoar" ]
			then
			potionused="yes"
			echo "$name is now immune to the basilisk's powerful stare"
			rm $collected/+potion-of-bezoar
			PS1="[ $name: $health $attack $defense ] "
			echo "press any button to continue"
			read hi
			clear
			else 
			echo "The potion-of-bezoar is not currently collected"
			echo "press any button to continue"
			read hi
			clear
			fi
		;;
		7)
			if [ -e "$collected/+medium-health-potion" ]
			then
			health=$(( $health + 20 ));
			if [ "$health" -gt "$maxhealth" ]
			then
			health=$(( $maxhealth ));
			fi
			echo "$name healed"
			rm $collected/+medium-health-potion
			PS1="[ $name: $health $attack $defense ] "
			echo "press any button to continue"
			read hi
			clear
			else 
			echo "The medium-health-potion is not currently collected"
			echo "press any button to continue"
			read hi
			clear
			fi
		;;
	esac
	clear
	}
function equip() { 
	echo "Enter armor to be equipped (if it is inside of collected)"
	echo "
	0. none
	1. +rusted-platemail
	2. +platemail
	3. +blessed-platemail
	"
	read choice
	case $choice in
		*)
			echo "no change in defense"
			echo "press any button to continue"
			read hi
			clear
		;;
		1)
			if [ -e "$collected/+rusted-platemail" ]
			then
			defense=$(( $defense + 2 ));
			echo "Defense increased"
			rm $collected/+rusted-platemail
			PS1="[ $name: $health $attack $defense ] "
			echo "press any button to continue"
			read hi
			clear

			else 
			echo "The chosen platemail is not currently collected"
			echo "press any button to continue"
			read hi
			clear

			fi
		;;
		2)
			if [ -e "$collected/+platemail" ]
			then 
			defense=$(( $defense + 4 ));
			echo "Defense increased"
			rm $collected/+platemail
			PS1="[ $name: $health $attack $defense ] "
			echo "press any button to continue"
			read hi
			clear
			else 
			echo "The chosen platemail is not currently collected"
			echo "press any button to continue"
			read hi
			clear
			fi
		;;
		3)
			if [ -e "$collected/+blessed-platemail" ]
			then
			defense=$(( $defense + 6 ));
			echo "Defense increased"
			rm $collected/+blessed-platemail
			PS1="[ $name: $health $attack $defense ] "
			echo "press any button to continue"
			read hi
			clear
			else 
			echo "The chosen platemail is not currently collected"
			echo "press any button to continue"
			read hi
			clear
			fi
		;;
	esac
	clear
	}
function quit() {  move_items; true_reset; cd $location; PS1="[\u@\h \W]$ "; }

tput smcup
while [[ $REPLY != "c" ]]
do
clear 
cat <<EOF                                                                                    
 _                                    _           __    ____                                      _  _ 
| |                                  | |        /  _|  / __ \                                    | || |
| |      ___   __ _   ___  _ __    __| |   ___  | |_  | /  \ /  ___   _ __  _ __  __      __ _ __| || |
| |     / _ \ / _  | / _ \|  _  \ / _  |  / _ \ |  _| | |     / _ \ |  __||  _  \\ \ /\ / // _  || || |
| |____|  __/| (_| ||  __/| | | || (_| | | (_) || |   | \__/\| (_) || |   | | | | \ V  V /| (_| || || |
\_____/ \___| \__, | \___||_| |_| \__,_|  \___/ |_|    \____/ \___/ |_|   |_| |_|  \_/\_/  \__,_||_||_|
               __/ |                                                                                  
              |___/     
	     	      		              Menu
					~~~~~~~~~~~~~~~~~
					a. Start Game
					b. About Game
					c. Quit


EOF
	read -p "Enter choice [a-c]: " choice
	#move_items
	reset_var
	
	case $choice in 
	a) echo "Your Story can now begin"
	
	read -p "Enter a name of the Legend: " name
	
	sleep 1;
	echo "Excellent. Now it is time to tell the story of our new hero $name."
	sleep 1;
	echo "(If at any point you need to exit the game, just type 'quit' .)"
	PS1="[ $name: $health $attack $defense ] "
	echo "[ $health $attack $defense ] "
	echo "  ^This first value shows your current health"
	sleep 1;
	echo "[ $health $attack $defense ] "
	echo "     ^This second value shows your current attack"
	sleep 1;
	echo "[ $health $attack $defense ] "
	echo "       ^This third value shows your current defense"
	sleep 1;
	echo ""
	echo "press any button to continue"
	read hi
	echo "\(This game does require you to search around for items. "
	echo "Make sure to pick them up along the way, as they will be needed for you to continue on your journey.\)"
	. .start
	;;
	b) clear 
	echo "Legend of Cornwall is a terminal based game that was made to showcase a few basics commands used in the linux terminal."
	sleep 1;
	echo "This is done so that the player can learn a bit about how to utilize the bash shell in an entertaining way."
	sleep 1;
	echo "your goal as the hero of this story is to explore this mystical forest and confront the evil being causing more and more evils to infect this peaceful land."
	sleep 1;
	echo "If you wish to avoid seeing and altering any of the game code be sure to follow the games instructions."
	sleep 1;
	echo "Press any button to select a different option"
	read hi
	
	;;
	c) 
	tput rmcup
	echo "Exiting Game"
	sleep 1;
	break
	;;
	*) 
	echo "Invalid Option: Press any button to return then make sure to enter only [a-c] for this menu. "
	read hi
	;;
esac
done
