#!bin/bash/

#(Arriving at Church) - move to Church Directory 

echo "Merlin waves his hand and trees wiggle at a V shape."
sleep 1;
echo "You move through and travel along until you come across an entrance into the back of the church."
sleep 1;
echo "You look ahead to see a giant interior of a rustic chapel, seeing a giant silhouette of the Lady from the Lake."
sleep 1;
echo "Below, you see three imps crowding around the egg placed on the pulpit. You preceed to aim your sword and walk towards them."
sleep 1;
echo "They get alarmed and engage into combat."
sleep 1;
tput bold; echo "This part is not implemented yet. The final product will show a system of confrontation."; tput sgr0;
sleep 1;
echo "The get scared and scurry away out the front door, leaving the egg alone."
sleep 1;
echo "You proceed to grab the egg and quickly exit through the front door, holding your sword out to make sure no imps are hiding."
sleep 1;
