#!bin/bash/

#Option 2 (Garden) - move to Garden Directory

echo "You head to the entrance of a garden, seeing many lush plants and bushes laying about with another crossroads."
sleep 1;
echo "Directly in the center, you see a statue of a half-horse half-human creature. You approach it, noticing a bird sitting ontop of it."
sleep 1;
echo "However, this bird appears to be glowing with a fire hue. As you move towards the bird, it flies towards the right path."
sleep 1;
read -p "Which path do you go?[left or right]: " selectionA
      case $selectionA in
      left)
            echo "You choose to run after it, following the right path."
            sleep 1;
            ;;
      right)
            echo "As you look to start heading down the left path, the amulet speaks to you."
            sleep 1;
            tput bold; echo "Mysterious Voice: "; tput srg0; echo "Do not head here yet, you need to follow the phoenix."
            sleep 1;
            echo "As you listen to the words of the unknown voice, you proceed right onwards to where the phoenix is going."
            sleep 1;
            ;;
esac
