#!bin/bash/

#(Arriving Castle) - move to Castle Directory 

echo "You and the griffen land on the balcony."
sleep 1;
echo "You hop off and send the griffen away from danger."
sleep 1;
echo "You pull out the potion Merlin gave you and drink it. You then feel a rush of energy."
sleep 1;

#(move into castle room)

echo "You walk forward into a dimly lit cathedral."
sleep 1;
echo "This massive enclosure high above the castle is spacious, lineing the walls with medieval apparel."
sleep 1;
echo "You look around to see the embellishment and notice a path straight ahead leading to a shadowy figure positioned large with white eyes only vibrant."
sleep 1;
echo "The eyes begin to engulf with a red hue, shining a beam directly towards you."
sleep 1;
echo "The beam bounces off your body and hits a wall, dessipating as it comes into contact."
sleep 1;
echo "The serpernt looks at the dissolve, turning back at you with anger. His rage shakes the ground as he travels towards you."
sleep 1;
echo "You pull out Excalibur and raise it high, for which the basilisk immediately stops slithering and senses an embodiment of hatred."
sleep 1;
echo "You see him full charge at you, engaging yourself into a final showdown."
sleep 1;
tput bold; echo "This part is not implemented yet. The final product will show a system of confrontation."; tput sgr0;
sleep 1;
echo "The snake readies his last move, wrapping his tail around you and lifting you upwards."
sleep 1;
echo "You get whiplash, but immediately maintain you senses as you struggle to break free."
sleep 1;
echo "The snake raises you towards his mouth, preparing to engulf you. You eventually break free, moving the sword outward to slice off its tail."
sleep 1;
echo "The Basilisk screams in agony, dropping you to the ground as the sword leaves your hand."
sleep 1;
echo "With a thud on the ground, the creature lunges at you with the strength it has left."
sleep 1;
echo "You reach for the sword, grabbing it, and pointing it at the head of the creature."
sleep 1;
echo "The beast lands straight through it, killing him instantly."
sleep 1;
echo "With this, you realize that the creature has perished ontop of you."
sleep 1;
echo "You move the beast aside and pull the sword out of its head."
sleep 1;
echo "You look forward to see the amulet move outward and face you one final time."
sleep 1;

#(go back to balcony)

tput bold; echo "Merlin: "; tput sgr0; echo "Thank you for your saving Cornwall from the Basilisk."
sleep 1;
echo "You have my deference, Arthur. The griffen is awaiting for you outside."
sleep 1;
echo "He shall take you to the townspeople, who thank you for your efforts."
sleep 1;
echo "You look as the amulet evaporates infront of you, vanishing into a particle of blue dust."
sleep 1;
echo "You then head out onto the balcony, to which the griffen awaits."
sleep 1;
echo "You climb ontop of the griffen, telling it to take you away."
sleep 1;
echo "She soars into the sky, showing a beautiful view of the safer landscape."
sleep 1;
echo "As you travel along, you are glad that you were able to do justice for all those living in the great land of Cornwall."
sleep 1;
