#!/bin/bash

#(Arriving Castle) - move to Castle Directory

echo "You and the griffen land on the balcony."
sleep 1;
echo "You hop off and send the griffen away from danger."
sleep 1;

#(move into castle room)
echo "You walk forward into a dimly lit cathedral."
sleep 1;
echo "This massive enclosure high above the castle is spacious, lineing the walls with medieval apparel."
sleep 1;
echo "You look around to see the embellishment and notice a path straight ahead leading to a shadowy figure positioned large with white eyes only vibrant."
sleep 1;
echo "The eyes begin to engulf with a red hue, shining a beam directly towards you."
sleep 1;
if [ "$potionused" = "yes" ]
then
echo "The beam bounces off your body and hits a wall, dissipating as it comes into contact with the wall."
sleep 1;
echo "The serpernt looks at the dissolve, turning back at you with anger. His rage shakes the ground as he travels towards you."
sleep 1;
echo "You pull out Excalibur and raise it high, for which the basilisk immediately stops slithering and senses an embodiment of hatred."
sleep 1;
echo "You see him full charge at you, engaging yourself into a final showdown."




#COMBAT HERE

echo "You have two choices: "
sleep 1;
echo "A) Retreat and explore to better equip yourself    B) Fight the basilisk"
read ans
if [ $ans = 'B' ] || [ $ans = 'b' ]
then
echo " "
echo " "
echo "You will fight the basilisk by rolling random numbers between 0-10, the basilisk has a health of 70"
sleep 1;
echo "Each time you strike the basilisk it hits back."
sleep 1;
echo "If you use an item the basilisk will still attack you"
sleep 1;
clear
PlayerHealth=$(( $health ));
BasiliskHealthTotal=70;
while [ $BasiliskHealthTotal -gt 0 ] && [ $PlayerHealth -gt 0 ]
do
echo " "
PS1="[ $name: $PlayerHealth $attack $defense ] "
echo "Player Health: $PlayerHealth   Basilisk Health Total: $BasiliskHealthTotal"
echo "Press A to Attack, B to useitem: "
read response
if [ $response = 'A' ] || [ $response = 'a' ]
then
DIV=$((10+1));
DIV=$((10+1));
RandAttack=$(($RANDOM%$DIV + $attack));
BasiliskHealthTotal=$(($BasiliskHealthTotal-$RandAttack));
DIV2=$((10+1));
RandAttack2=$(($RANDOM%$DIV2 - $defense));
if [ $RandAttack2 -lt 0 ]
then
RandAttack2=0
fi
PlayerHealth=$(($PlayerHealth-$RandAttack2));
elif [ $response = 'B' ] || [ $response = 'b' ]
then
useItem
RandAttack2=$(($RANDOM%$DIV2 - $defense))
if [ $RandAttack2 -lt 0 ]
then
RandAttack2=0
fi
PlayerHealth=$(($PlayerHealth-$RandAttack2))
else
echo " "
echo "Your indecision costs you as the basilisk gets a free hit"
RandAttack2=$(($RANDOM%$DIV2 - $defense))
if [ $RandAttack2 -lt 0 ]
then
RandAttack2=0
fi
PlayerHealth=$(($PlayerHealth-$RandAttack2))
fi
if [ $BasiliskHealthTotal -le 29 ]
then
if [ $BasiliskHealthTotal -le 9 ]
then
echo "The Basilisk nears death, finish this!"
else
echo "The Basilisk grows weary!"
fi
fi
if [ $PlayerHealth -le 0 ]
then
echo " "
echo "You have been defeated"
fi
if [ $BasiliskHealthTotal -le 0 ]
then
#Victory
echo " "
sleep 1;
tput sgr0; echo "The basilisk readies his last move, wrapping his tail around you and lifting you upwards."
sleep 1;
echo "You get whiplash, but immediately maintain you senses as you struggle to break free."
sleep 1;
echo "The snake raises you towards his mouth, preparing to engulf you. You eventually break free, moving the sword outward to slice off its tail."
sleep 1;
echo "The Basilisk screams in agony, dropping you to the ground as the sword leaves your hand."
sleep 1;
echo "With a thud on the ground, the creature lunges at you with the strength it has left."
sleep 1;
echo "You reach for the sword, grabbing it, and pointing it at the head of the creature."
sleep 1;
echo "The beast lands straight through it, killing him instantly."
sleep 1;
echo "With this, you realize that the creature has perished ontop of you."
sleep 1;
echo "You move the beast aside and pull the sword out of its head."
sleep 1;
echo "You look forward to see the amulet move outward and face you one final time."
sleep 1;
tput bold; echo "Merlin: "; tput sgr0; echo "Thank you for your saving Cornwall from the Basilisk."
sleep 1;
echo "You have my deference, Arthur. The griffen is awaiting for you outside."
sleep 1;
echo "He shall take you to the townspeople, who thank you for your efforts."
sleep 1;
echo "You look as the amulet evaporates infront of you, vanishing into a particle of blue dust."
sleep 1;
echo "You then head out onto the balcony, to which the griffen awaits."
sleep 1;
echo "You climb ontop of the griffen, telling it to take you away."
sleep 1;
echo "She soars into the sky, showing a beautiful view of the safer landscape."
sleep 1;
echo "As you travel along, you are glad that you were able to do justice for all those living in the great land of Cornwall."
sleep 1;
tput bold; echo "                            VICTORY                            "
tput sgr0; echo "---------------------------------------------------------------"
sleep 1;
tput bold; echo "Congratulations you have finished The Legend of Cornwall."
sleep 1;
echo "If you missed the initial Syren combat be sure to go back and try it out!"
sleep 1;
echo "It's a fun little combat with some interesting changes from the other combats."
sleep 1;
echo "If you want to play this combat enter 'notice' in the DeepLake section of the game"
sleep 1;
echo "And thank you so much for playing it really means a lot that you spent your time getting this far!"
sleep 1;
echo "Press any button to reset the game"
read hi
clear
quit
#End Victory
fi
done
else
#Retreat
echo " "
echo " "
echo "You have chosen to retreat and to gear up. Good luck, use ./@Castle1 to"
sleep 1;
echo "Attempt the fight with the basilisk again."
sleep 1;
echo "( The basilisk must be defeated to proceed )"
#End Retreat
fi
if [ $health -le 0 ]
then
#Lose life
lives=$(( $lives - 1 ));
echo "You have lost a life."
sleep 1;
echo "$lives lives remaining."
sleep 1;
if [ "$lives" = "0" ]
then
#Lose all lives
echo "You Have lost all lives."
tput bold; echo "                               Game Over                               "
tput sgr0; echo "-----------------------------------------------------------------------"
echo "be more careful next time"
echo "Press any button to reset the game"
read hi
clear
quit
fi
health=$(( $maxhealth ));
PS1="[ $name: $health $attack $defense ] ";
fi


#End Combat

#Death state from not using the potion before confronting the Basilisk
else
echo "The beam shoots directly into you, as you look towards the Basilisk you can see it almost seem to smirk."
sleep 1;
echo "Your body starts to turn rigid as you look down and find yourself turning to stone."
sleep 1;
echo "Your last thoughts are occupied only by the mistake you made by forgetting to use merlins potion before this fight"
sleep 1;
tput bold; echo "                               Game Over                               "
tput sgr0; echo "-----------------------------------------------------------------------"
echo "Press any button to reset the game"
read hi
clear
quit
fi
#(go back to balcony)
