#!bin/bash/

#Option 1 (Deep Lake) - move to Deep Lake Directory

echo "You proceed leftward as the lady directed."
sleep 1;
echo "Following closely along the edge of the lake to a more dark blue area with a huge waterfall."
sleep 1;
echo "There lay in the center of the lake a massive stone outcropping with a rod pointed out of it."
sleep 1;
echo "You carefully navigate towards it, without falling in to the surrounding water."
sleep 1;
echo "Climbing up the mound, you notice a voice singing to you." 
sleep 1;
read -p "What do you do?[continue or notice]: " selection5
        case $selection5 in
        continue)
              echo "You proceed on the long climb to the top, keeping your determination. "
              sleep 1;
              echo "You see a sword upon the rock plunged bladefirst into the stone. "
              sleep 1;
              echo "You try to pull it out, at which point to your surprise it slips free easily, in contrast with the unyielding and seemingly unmovable stone. "
              sleep 1;
              echo "When released. The singing halts to a stop. "
              sleep 1;
              echo "You turn towards the direction of where the singing originated, noting a fish-like woman's head staring at you. "
              sleep 1;
              echo "She then dives underneath the water as you look on in confusion."
              sleep 1;
              echo "You turn towards the now free sword and read the word | Excalibur | engraved on it's side. "
              sleep 1;
              tput bold; echo "Amulet: "; tput sgr0; echo "make sure to collect that sword it will be hopeless for you to succeed without it"
              mv .+excalibur \+excalibur
              mv $location/locations/cave/barn/lake/.@Lake2 $location/locations/cave/barn/lake/@Lake2
              ;;
        notice)
              echo "You turn to see a fish-like human being, staring at you."
              sleep 1;
              echo "You feel the urgue to head towards her."
              sleep 1;
              echo "But as soon as you take one step down towards her, a hand grabs your ankle as a terrifying hiss comes from below."
              sleep 1;
              echo "Startled, you look down to see the menacing physique of a similar creature with a firm grasp on your foot,"
              echo "hissing and preparing to rip your foot apart with it's razor sharp teeth. "
              sleep 1;
              echo "You manage the strength to yank your foot away and glance quickly around to see multiple mermaids coming towards you."
              sleep 1;
              echo "You quickly climb the mound to get higher ground, seeing the sword in a stone. "
              sleep 1;
              echo "You scramble towards the stone and immediately try pulling it out, upon which the sword slides out smoothly. "
              sleep 1;
              echo "The creatures all hiss at you as you aim it in their directions, drawing you into a battle against three different syrens."
              sleep 1;
              mv .+excalibur \+excalibur
              mv +excalibur /$collected
              echo " "
              echo " "
              echo "You will fight the syrens by rolling random numbers between 0-10, the skeletons each have a health of 15"
              sleep 1;
              echo "Each time you strike one skeleton it hits back with a hit of 5, you have a health of $health. "
              sleep 1;
              echo "If you use an item the skeletons will still attack you"
              sleep 1;
              echo "Basically, you must roll 30 total points in 5 turns (each turn is up to 10 points) Good Luck!"
              sleep 1;
              echo "Be warned you have $lives lives and if you lose $lives battles you will have to restart the game."
              sleep 1;
              echo "However by winning a combat you will earn a life."
              echo "press any button to begin"
              read hi
              clear
              PlayerHealth=$(( $health ));
              SyrenHealthTotal=45;
              while [ $SyrenHealthTotal -gt 0 ] && [ $PlayerHealth -gt 0 ]
              do
              echo " "
              PS1="[ $name: $PlayerHealth $attack $defense ] "
              echo "Player Health: $PlayerHealth   Syren Health Total: $SyrenHealthTotal"
              echo "Press A to Attack, B to useitem: "
              read response
              if [ $response = 'A' ] || [ $response = 'a' ]
              then
              DIV=$((10+1));
              RandAttack=$(($RANDOM%$DIV + $attack));
              SyrenHealthTotal=$(($SyrenHealthTotal-$RandAttack));
              DIV2=$((7+1));
              RandAttack2=$(($RANDOM%$DIV2 - $defense));
              if [ $RandAttack2 == 8 ]
              then 
              echo "The syrens aluring song stops you mid attack as you are put in a trance and they proceed to freely hit you."
              sleep 1;
              SyrenHealthTotal=$(($SkeletonHealthTotal+$RandAttack));
              fi
              if [ $RandAttack2 -lt 0 ]
              then
              RandAttack2=0
              fi
              PlayerHealth=$(($PlayerHealth-$RandAttack2));
              elif [ $response = 'B' ] || [ $response = 'b' ]
              then
              useItem
              RandAttack2=$(($RANDOM%$DIV2 - $defense))
              if [ $RandAttack2 -lt 0 ]
              then
              RandAttack2=0
              fi
              PlayerHealth=$(($PlayerHealth-$RandAttack2))
              else
              echo " "
              echo "Your indecision costs you as the syrens gets a free hit"
              RandAttack2=$(($RANDOM%$DIV2 - $defense))
              if [ $RandAttack2 -lt 0 ]
              then
              RandAttack2=0
              fi
              PlayerHealth=$(($PlayerHealth-$RandAttack2))
              fi
              if [ $SyrenHealthTotal -le 29 ]
              then
              if [ $SyrenHealthTotal -le 14 ]
              then
              echo "Only one Syren remains!"
              else
              echo "Only two Syrens remain!"
              fi
              fi
              if [ $PlayerHealth -le 0 ]
              then
              echo " "
              echo "You have been defeated"
              fi
              if [ $SyrenHealthTotal -le 0 ]
              then
              echo " "
              echo "Congratulations, You have defeated all three syrens"
              sleep 1;
              echo "with the syrens defeated you suddenly feel a burst of energy"
              sleep 1;
              echo "$name healed and health increased"
              maxhealth=$(( $maxhealth + 5 ));
              health=$(( $maxhealth ));
              lives=$(( $lives + 1 ));
              PS1="[ $name: $health $attack $defense ] ";
              mv $location/locations/cave/barn/lake/.@Lake2 $location/locations/cave/barn/lake/@Lake2
              fi
              if [ "$Playerhealth" = "0" ] || [ $Playerhealth -lt 0 ]
              then
              lives=$(( $lives - 1 ));
              echo "You have lost a life."
              sleep 1;
              echo "$lives lives remaining."
              sleep 1;
              if [ "$lives" = "0" ]
              then 
              echo "You Have lost all lives."
              tput bold; echo "                               Game Over                               "
              tput sgr0; echo "-----------------------------------------------------------------------"
              echo "be more careful next time"
              echo "Press any button to reset the game"
              read hi
              clear 
              quit
              fi
              fi
              done
              health=$(( $maxhealth ));
              PS1="[ $name: $health $attack $defense ] ";
              echo "The remaining syrens flee in fear as you stand there in suprise of your successful vanquish."
              sleep 1;
              echo "You look at the sword and see the engraving on the side | Excalibur |. "
              sleep 1;
              echo "press any button to continue"
              read hi
              clear
              ;;
          *) 
              echo "Unsure of what you do you are instinctively drawn to the beautiful song that is coming from all around you"
              sleep 1;
              echo "You turn to see a fish-like human being, staring at you."
              sleep 1;
              echo "You feel the urgue to head towards her."
              sleep 1;
              echo "But as soon as you take one step down towards her, a hand grabs your ankle as a terrifying hiss comes from below."
              sleep 1;
              echo "Startled, you look down to see the menacing physique of a similar creature with a firm grasp on your foot, 
              hissing and preparing to rip your foot apart with it's razor sharp teeth. "
              sleep 1;
              echo "You manage the strength to yank your foot away and glance quickly around to see multiple mermaids coming towards you."
              sleep 1;
              echo "You quickly climb the mound to get higher ground, seeing the sword in a stone. "
              sleep 1;
              echo "You scramble towards the stone and immediately try pulling it out, upon which the sword slides out smoothly. "
              sleep 1;
              echo "The creatures all hiss at you as you aim it in their directions, drawing you into a battle against three different sirens."
              sleep 1;
              mv .+excalibur \+excalibur
              mv +excalibur \$collected
              echo " "
              echo " "
              echo "You will fight the syrens by rolling random numbers between 0-10, the skeletons each have a health of 15"
              sleep 1;
              echo "Each time you strike one skeleton it hits back with a hit of 5, you have a health of $health. "
              sleep 1;
              echo "If you use an item the skeletons will still attack you"
              sleep 1;
              echo "Basically, you must roll 30 total points in 5 turns (each turn is up to 10 points) Good Luck!"
              sleep 1;
              echo "Be warned you have $lives lives and if you lose $lives battles you will have to restart the game."
              sleep 1;
              echo "However by winning a combat you will earn a life."
              echo "press any button to begin"
              read hi
              clear
              PlayerHealth=$(( $health ));
              SyrenHealthTotal=45;
              while [ $SyrenHealthTotal -gt 0 ] && [ $PlayerHealth -gt 0 ]
              do
              echo " "
              PS1="[ $name: $PlayerHealth $attack $defense ] "
              echo "Player Health: $PlayerHealth   Syren Health Total: $SyrenHealthTotal"
              echo "Press A to Attack, B to useitem: "
              read response
              if [ $response = 'A' ] || [ $response = 'a' ]
              then
              DIV=$((6+1));
              RandAttack=$(($RANDOM%$DIV + $attack));
              SyrenHealthTotal=$(($SyrenHealthTotal-$RandAttack));
              DIV2=$((7+1));
              RandAttack2=$(($RANDOM%$DIV2 - $defense));
              if [ "$RandAttack2" == 8 ] || [ "$RandAttack2" == 4 ]
              then 
              echo "The syrens aluring song stops you mid attack as you are put in a trance and they proceed to freely hit you."
              sleep 1;
              SyrenHealthTotal=$(($SkeletonHealthTotal+$RandAttack));
              fi
              if [ "$RandAttack2" -lt 0 ]
              then
              RandAttack2=0
              fi
              PlayerHealth=$(($PlayerHealth-$RandAttack2));
              elif [ $response = 'B' ] || [ $response = 'b' ]
              then
              useItem
              RandAttack2=$(($RANDOM%$DIV2 - $defense))
              if [ "$RandAttack2" -lt 0 ]
              then
              RandAttack2=0
              fi
              PlayerHealth=$(($PlayerHealth-$RandAttack2))
              else
              echo " "
              echo "Your indecision costs you as the syrens gets a free hit"
              RandAttack2=$(($RANDOM%$DIV2 - $defense))
              if [ $RandAttack2 -lt 0 ]
              then
              RandAttack2=0
              fi
              PlayerHealth=$(($PlayerHealth-$RandAttack2))
              fi
              if [ $SyrenHealthTotal -le 29 ]
              then
              if [ $SyrenHealthTotal -le 14 ]
              then
              echo "Only one Syren remains!"
              else
              echo "Only two Syrens remain!"
              fi
              fi
              if [ $PlayerHealth -le 0 ]
              then
              echo " "
              echo "You have been defeated"
              fi
              if [ $SyrenHealthTotal -le 0 ]
              then
              echo " "
              echo "Congratulations, You have defeated all three skeletons"
              sleep 1;
              echo "with the skeletons defeated you suddenly feel a burst of energy"
              sleep 1;
              echo "$name healed and health increased"
              maxhealth=$(( $maxhealth + 5 ));
              health=$(( $maxhealth ));
              lives=$(( $lives + 1 ));
              PS1="[ $name: $health $attack $defense ] ";
              echo "After your encounter with the tree skeletons, you are forced to back away as many more rise to take their place and outnumber you 10 to 1."
              sleep 1;
              echo "You hurry out of the graveyard to tell Merlin of this new development."
              mv $location/locations/cave/barn/lake/.@Lake2 $location/locations/cave/barn/lake/@Lake2
              fi
              if [ "$Playerhealth" = "0" ] || [ "$Playerhealth" -lt 0 ]
              then
              lives=$(( $lives - 1 ));
              echo "You have lost a life."
              sleep 1;
              echo "$lives lives remaining."
              sleep 1;
              if [ "$lives" = "0" ]
              then 
              echo "You Have lost all lives."
              tput bold; echo "                               Game Over                               "
              tput sgr0; echo "-----------------------------------------------------------------------"
              echo "be more careful next time"
              echo "Press any button to reset the game"
              read hi
              clear 
              quit
              fi
              fi
              done
              health=$(( $maxhealth ));
              PS1="[ $name: $health $attack $defense ] ";
              echo "The remaining syrens flee in fear as you stand there in suprise of your successful vanquish."
              sleep 1;
              echo "The remaining syrens flee in fear as you stand there in suprise of your successful vanquish. You look at the sword and see the engraving on the side | Excalibur |. "
              echo "You look at the sword and see the engraving on the side | Excalibur |. "
              sleep 1;
              ;;
          
esac
mv $location/locations/cave/barn/lake/.@Lake2 $location/locations/cave/barn/lake/@Lake2
echo "press any button to continue"
read hi
clear
