#!bin/bash/

#Option 1 (Deep Lake) - move to Deep Lake Directory

echo "You proceed leftward as the lady directed."
sleep 1;
echo "Following closely along the edge of the lake to a more dark blue area with a huge waterfall."
sleep 1;
echo "There lay in the center of the lake a massive stone outcropping with a rod pointed out of it."
sleep 1;
echo "You carefully navigate towards it, without falling in to the surrounding water."
sleep 1;
echo "Climbing up the mound, you notice a voice singing to you." 
sleep 1;
read -p "What do you do?[continue or notice]: " selection5
        case $selection5 in
        continue)
              echo "You proceed on the long climb to the top, keeping your determination. "
              sleep 1;
              echo "You see a sword upon the rock plunged bladefirst into the stone. "
              sleep 1;
              echo "You try to pull it out, at which point to your surprise it slips free easily, in contrast with the unyielding and seemingly unmovable stone. "
              sleep 1;
              echo "When released. The singing halts to a stop. "
              sleep 1;
              echo "You turn towards the direction of where the singing originated, noting a fish-like woman's head staring at you. "
              sleep 1;
              echo "She then dives underneath the water as you look on in confusion."
              sleep 1;
              echo "You turn towards the now free sword and read the word | Excalibur | engraved on it's side. "
              sleep 1;
              tput bold; echo "Amulet: "; tput sgr0; echo "make sure to collect that sword it will be hopeless for you to succeed without it"
              mv .excalibur \excalibur
              ;;
        notice)
              echo "You turn to see a fish-like human being, staring at you."
              sleep 1;
              echo "You feel the urgue to head towards her."
              sleep 1;
              echo "But as soon as you take one step down towards her, a hand grabs your ankle as a terrifying hiss comes from below."
              sleep 1;
              echo "Startled, you look down to see the menacing physique of a similar creature with a firm grasp on your foot, 
              hissing and preparing to rip your foot apart with it's razor sharp teeth. "
              sleep 1;
              echo "You manage the strength to yank your foot away and glance quickly around to see multiple mermaids coming towards you."
              sleep 1;
              echo "You quickly climb the mound to get higher ground, seeing the sword in a stone. "
              sleep 1;
              echo "You scramble towards the stone and immediately try pulling it out, upon which the sword slides out smoothly. "
              sleep 1;
              echo "The creatures all hiss at you as you aim it in their directions, drawing you into a battle against three different sirens."
              sleep 1;
              mv .excalibur \excalibur
              mv excalibur \$collected
              attack="10"
              tput bold; echo "This part is not implemented yet. The final product will show a system of confrontation."; tput sgr0;
              sleep 1;
              echo "They all leave in fear as you stand there in suprise of your successful vanquish. You look at the sword and see the engraving on the side | Excalibur |. "
              sleep 1;
              ;;
              
esac
