#!/bin/bash
clear
r=$(( $RANDOM % 4 )) #should give r a random number between 1 and 3

case $r in 
	1) cp $location/collection/.Health-Potion $location/usables/Health-Potion
	echo "You found a Health Potion"
	;;
	2) cp $location/collection/.Attack-Potion $location/usables/Attack-Potion
	echo "You found a Attack Potion"
	;;
	3) cp $location/collection/.Defense-Potion $location/usables/Defense-Potion
	echo "You found a Defense Potion"
	;;
