#!bin/bash/

#(Arriving at barn) - move to Barn Directory 
if [ -e key $location/collected ]; then
echo "You come across the chest sitting in the corner of the barn. 
With the skull engraving on the lock matching the skull-shape of the key, you go to unlock it. 
You open the lid and come across the herb Merlin asked for. 
You grab it and leave the barn."

else 
echo "The chest is locked up tight the only way to open it seems to come from the skull shaped lock engraved on the surface."
