#!bin/bash/

#(Arriving at barn) - move to Barn Directory 

echo "You come across the chest sitting in the corner of the barn. With the skull engraving on the lock matching the skull-shape of the key, you go to unlock it. You open the lid and come across the herb Merlin asked for. You grab it and leave the barn."
