#!bin/bash/

#(re enter cemetery) - move to Cemetery Directory

echo "You re-enter the cemetery to still see the skeletons surrounding the statue, but they immediately draw fear from the centuar."
sleep 1;
scho "The phoenix stays close to you as the centaur prepares to charge them."
sleep 1;
echo "The skeletons all run amok, allowing you to go to the angel statue."
sleep 1;
echo "You go close to it and reach out your hand to grab the key."
sleep 1;
echo "You proceed to hold the key in your hand, when a skeleton grabs the end."
sleep 1;
echo "You both pull back and forth between who has it, the key slips from both of your hands and lands on a nearby tombstone.
You and the skeleton draw your weapons as more approach to fight."
sleep 1;
tput bold; echo "This part is not implemented yet. The final product will show a system of confrontation."; tput sgr0;
sleep 1;
"The last remaining skeleton uses its last strength to crawl towards the key, but before it can reach the key it gets rammed by the centaur statue."
sleep 1;
echo "This causes the skeleton to explode into bones that are flung everywhere, the key being left shining on the tombstone"
mv .@key /key
