#!/bin/bash
#(To the cemetery) - move to Cemetery Directory

echo "You enter the cemetery and see rows of tombstones."
sleep 1
echo "You look around and see another similar statue to the human-horse in the garden."
sleep 1;
echo "This one seems to resemble the Lady of the Lake, with her hand reaching out."
sleep 1;
echo "In her hand, she has hold of a key mentioned by Merlin."
sleep 1;
echo "You move towards it, but stop when the ground begins to shake."
sleep 1;
echo "You see hands popping out from some of the graves."
sleep 1;
echo "You begin to see skeletons climbing out and moving towards the statue, as if they are trying to protect it."
sleep 1;
echo "Three skeletons rush towards you."
sleep 1;
echo " "
echo " "
echo "You have two choices: "
sleep 1;
echo "A) Retreat and explore to better equip yourself    B) Fight the three skeletons"
read ans
if [ $ans = 'B' ] || [ $ans = 'b' ]
then
echo " "
echo " "
echo "You will fight the skeletons by rolling random numbers between 0-10, the skeletons each have a health of 10"
sleep 1;
echo "Each time you strike one skeleton it hits back with a hit of 5, you have a health of 25. "
sleep 1;
echo "If you use an item the skeletons will still attack you"
sleep 1;
echo "Basically, you must roll 30 total points in 5 turns (each turn is up to 10 points) Good Luck!"
sleep 1;
clear
PlayerHealth=$(( $health ));
SkeletonHealthTotal=30;
while [ $SkeletonHealthTotal -gt 0 ] && [ $PlayerHealth -gt 0 ]
do
echo " "
PS1="[ $name: $PlayerHealth $attack $defense ] "
echo "Player Health: $PlayerHealth   Skeleton Health Total: $SkeletonHealthTotal"
echo "Press A to Attack, B to useitem: "
read response
if [ $response = 'A' ] || [ $response = 'a' ]
then
DIV=$((10+1));
RandAttack=$(($RANDOM%$DIV + $attack));
SkeletonHealthTotal=$(($SkeletonHealthTotal-$RandAttack));
DIV2=$((10+1));
RandAttack2=$(($RANDOM%$DIV2 - $defense));
if [ $RandAttack2 -lt 0 ]
then
RandAttack2=0
fi
PlayerHealth=$(($PlayerHealth-$RandAttack2));
elif [ $response = 'B' ] || [ $response = 'b' ]
then
useItem
RandAttack2=$(($RANDOM%$DIV2 - $defense))
if [ $RandAttack2 -lt 0 ]
then
RandAttack2=0
fi
PlayerHealth=$(($PlayerHealth-$RandAttack2))
else
echo " "
echo "Your indecision costs you as the skeleton gets a free hit"
RandAttack2=$(($RANDOM%$DIV2 - $defense))
if [ $RandAttack2 -lt 0 ]
then
RandAttack2=0
fi
PlayerHealth=$(($PlayerHealth-$RandAttack2))
fi
if [ $SkeletonHealthTotal -le 19 ]
then
if [ $SkeletonHealthTotal -le 9 ]
then
echo "Only one skeleton remains!"
else
echo "Only two skeletons remain!"
fi
fi
if [ $PlayerHealth -le 0 ]
then
echo " "
echo "You have been defeated"
fi
if [ $SkeletonHealthTotal -le 0 ]
then
echo " "
echo "Congratulations, You have defeated all three skeletons"
sleep 1;
echo "with the skeletons defeated you suddenly feel a burst of energy"
sleep 1;
echo "$name healed and health increased"
maxhealth=$(( $maxhealth + 5 ));
health=$(( $maxhealth ));
PS1="[ $name: $health $attack $defense ] ";
echo "After your encounter with the tree skeletons, you are forced to back away as many more rise to take their place and outnumber you 10 to 1."
sleep 1;
echo "You hurry out of the graveyard to tell Merlin of this new development."
mv $location/locations/cave/barn/lake/garden/merlin_tower/.@Merlin2 $location/locations/cave/barn/lake/garden/merlin_tower/@Merlin2 2>/dev/null
fi
done
echo " "
echo "Good luck exploring the cemetary, use ./Cemetery1 to"
echo "Interact with the three skeletons again in the future"
else
echo " "
echo " "
echo "You have chosen to retreat and keep gear up. Good luck, use ./Cemetary1 to"
echo "Interact with the three skeletons again in the future"
fi
echo "press any button to continue"
read hi
clear

