#!bin/bash/

#(re enter cemetery) - move to Cemetery Directory

echo "You re-enter the cemetery to still see the skeletons surrounding the statue, but they immediately draw fear from the centuar."
sleep 1;
scho "The phoenix stays close to you as the centaur prepares to charge them."
sleep 1;
echo "The skeletons all run amok, allowing you to go to the angel statue."
sleep 1;
echo "You go close to it and reach out your hand to grab the key."
sleep 1;
echo "You proceed to hold the key in your hand, when a skeleton grabs the end."
sleep 1;
echo "You both pull back and forth between who has it, proceeding in a duel."
sleep 1;
tput bold; echo "This part is not implemented yet. The final product will show a system of confrontation."; tput sgr0;
sleep 1;
"The skeleton uses its last strength to get a hold of it, but gets rammed by the centaur statue."
sleep 1;
echo "This causes the skeleton to explode bones everywhere and the key to fly in the air."
sleep 1;
echo "The phoenix flies towards it and grabs hold of the key, flying down to you and dropping it into your hand."
sleep 1;
echo "As the centaur is continuing with the other skeletons in the cemetery, you and the phoenix proceed to head back out."
sleep 1;
