#!bin/bash/

#(To the cemetery) - move to Cemetery Directory

echo "You soon enter the cemetery and see tombstones."
sleep 1;
echo "You look around and see another similar statue to the human-horse in the garden."
sleep 1;
echo "This one seems to resemble the Lady of the Lake, with her hand reaching out."
sleep 1;
echo "In her hand, she has hold of a key mentioned by Merlin."
sleep 1;
echo "You move towards it, but stop when the ground begins to shake."
sleep 1;
echo "You see hands popping out from some of the graves."
sleep 1;
echo "You begin to see skeletons climbing out and moving towards the statue, as if they are trying to protect it."
sleep 1;
echo "Three skeletons rush towards you."
sleep 1;
tput bold; echo "This part is not implemented yet. The final product will show a system of confrontation."; tput sgr0;
sleep 1;
echo "You began to feel overwhelmed with fighting, as more of them rise from the graves and come at you."
sleep 1;
echo "However, you are able to push them off of yourself enough to move away."
sleep 1;
echo "You turn around and leave hastily, hoping to ask Merlin for help."
sleep 1;
