#!bin/bash/

#(To the cemetery) - move to Cemetery Directory

echo "You soon enter the cemetery and see tombstones."
sleep 1
echo "You look around and see another similar statue to the human-horse in the garden."
echo "This one seems to resemble the Lady of the Lake, with her hand reaching out."
echo "In her hand, she has hold of a key mentioned by Merlin."
echo "You move towards it, but stop when the ground begins to shake."
echo "You see hands popping out from some of the graves."
echo "You begin to see skeletons climbing out and moving towards the statue, as if they are trying to protect it."
echo "You rush into they surrounding group, hoping to push past them."
echo "However, they are able to force you off and throw you to the ground."
echo "You turn around and leave, hoping to ask Merlin for help."  
