#!bin/bash/
echo "Deciding to follow them from behind, you come across a large church in the distance."
sleep 1;
echo "This rustic structure looks to be warn down. You do see the creatures heading inside."
sleep 1;
echo "And can just make out the last one as it looks back before closing the door with a slam."
sleep 1;
echo "You take note of its demonic features."
sleep 1;
echo "You approach the doors to which the little creatures entered."
sleep 1;
echo "You try pulling them open, but do not budge. You then stop and hear laughter coming from inside."
sleep 1;
echo "You try looking around the building, but find trees and fauna blocking their paths."
sleep 1;
echo "However, you do see a potion on the ground tilting on the side of the building."
mv .+health-potion $location/location/cave/barn/church/+health-potion
sleep 1;
echo "You then turn around and leave, heading back to the path towards the lake."
sleep 1;
echo "press any button to continue"
read 
clear
